#!/usr/bin/env python
"""
Regenerate gRPC Python stubs from the protos submodule into errepi/gen/.

Usage:
    python gen_protos.py

Run after bumping the protos submodule pointer (git -C protos pull && git add protos).
Generated files must be committed.

Note: the protos submodule is treated as read-only (protos are generated by
the server side). Both cron_bridge.proto and generic_regs.proto define an
AppInfo message in the same `protos` package, which collides in the process-wide
Python descriptor pool; generic_regs.proto is therefore compiled from a patched
copy where AppInfo is dropped and cron_bridge.proto is imported instead.
"""

import os
import re
import shutil
import sys
import tempfile

import grpc_tools.protoc


ROOT = os.path.dirname(os.path.abspath(__file__))
PROTOS_DIR = os.path.join(ROOT, "protos")
OUT_DIR = os.path.join(ROOT, "errepi", "gen")

GRPC_TOOLS_PROTO = os.path.join(os.path.dirname(grpc_tools.__file__), "_proto")

PROTO_FILES = [
    "cron_bridge.proto",
    "generic_regs.proto",
]

INCLUDES = [
    f"-I{PROTOS_DIR}",
    f"-I{GRPC_TOOLS_PROTO}",
]


def _patch_generic_regs(work_dir: str) -> None:
    """Write a patched copy of generic_regs.proto without its AppInfo message
    (duplicated in cron_bridge.proto) and with cron_bridge.proto imported."""
    with open(os.path.join(PROTOS_DIR, "generic_regs.proto")) as file:
        content = file.read()
    content = re.sub(
        r"\nmessage AppInfo \{[^}]*\}\n",
        "\n",
        content,
    )
    content = content.replace(
        'import "google/protobuf/empty.proto";',
        'import "cron_bridge.proto";\nimport "google/protobuf/empty.proto";',
    )
    with open(os.path.join(work_dir, "generic_regs.proto"), "w") as file:
        file.write(content)


def _compile(proto_file: str, includes) -> None:
    return_code = grpc_tools.protoc.main(
        [
            "grpc_tools.protoc",
            *includes,
            f"--python_out={OUT_DIR}",
            f"--grpc_python_out={OUT_DIR}",
            proto_file,
        ]
    )
    if return_code != 0:
        sys.exit(f"protoc failed on {proto_file} (exit {return_code})")


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, "__init__.py"), "w"):
        pass
    for proto_file in PROTO_FILES:
        if proto_file == "generic_regs.proto":
            work_dir = tempfile.mkdtemp(prefix="errepi-proto-")
            try:
                _patch_generic_regs(work_dir)
                _compile(proto_file, [f"-I{work_dir}", *INCLUDES])
            finally:
                shutil.rmtree(work_dir)
        else:
            _compile(proto_file, INCLUDES)
    _make_imports_relative(OUT_DIR)
    print(f"Generated stubs in {os.path.relpath(OUT_DIR, ROOT)}/")


def _make_imports_relative(package_dir: str) -> None:
    """grpc_tools emits absolute `import cron_bridge_pb2` / `from protos import ...`
    imports that only resolve when the generated package is installed as
    top-level `protos`. Rewrite them to package-relative imports so stubs
    work as errepi.gen."""
    for file_name in os.listdir(package_dir):
        if not (file_name.endswith("_pb2.py") or file_name.endswith("_pb2_grpc.py")):
            continue
        path = os.path.join(package_dir, file_name)
        with open(path) as file:
            content = file.read()
        content = re.sub(
            r"^import ([\w]+_pb2) as ([\w]+)$",
            r"from . import \1 as \2",
            content,
            flags=re.MULTILINE,
        )
        content = re.sub(
            r"^from protos import ([\w]+) as ([\w]+)$",
            r"from . import \1 as \2",
            content,
            flags=re.MULTILINE,
        )
        with open(path, "w") as file:
            file.write(content)


if __name__ == "__main__":
    main()
