[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "errepi-py"
version = "0.1.2"
description = "Python bindings for Errepi Net microservices"
authors = [
    { name = "Valerio Faiuolo", email = "valerio.faiuolo@errepinet.it" }
]
requires-python = ">=3.10,<4"
dependencies = [
    "pydantic>=2.0.0,<3.0.0",
    "grpcio>=1.60.0,<2.0.0"
]
keywords = ["errepinet", "microservices", "bindings"]

[dependency-groups]
dev = [
    "grpcio-tools>=1.60.0",
    "sphinx>=7.0.0",
    "sphinx-rtd-theme>=2.0.0"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["errepi*"]
